smarthome/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from watchapp import views

router = routers.DefaultRouter()
router.register(r'events', views.EventViewSet)
urlpatterns = [
    url(r'^watchapp/', include('watchapp.urls', namespace="watchapp")),
    url(r'^admin/', include(admin.site.urls)),
	url(r'^api/', include(router.urls)),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

watchapp/urls.py
from django.conf.urls import patterns, include, url
from watchapp import views
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic.base import TemplateView

urlpatterns = patterns('',
    #URLs index o para autenticacion
    url(r'^$', TemplateView.as_view(template_name='watchapp/index.html')),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', login, {'template_name': 'watchapp/login.html', }, name="login"),
    url(r'^login_success/$', views.login_success, name='login_success'),
    url(r'^logout/$', logout, {'template_name': 'watchapp/login.html', }, name="logout"),
	url(r'^sensorstatus/$', views.render_sensor_status, name='render_sensor_status'),
    url(r'^get_owner_reports/$', views.get_owner_reports, name='get_owner_reports'),
    url(r'^(?P<property_id>\d+)(?P<asresident>[a-zA-Z0-9]+)/change_secure_mode/$', views.change_secure_mode, name='change_secure_mode'),
	#URLs para funcionalidades de usuarios (residente/propietario)
    url(r'^users_home/$', views.users_home, name='users_home'),
    url(r'^sensor_configuration/$', views.sensor_configuration, name='sensor_configuration'),
	url(r'^update_sensor/$', views.update_sensor, name='update_sensor'),
	#URLs para funcionalidades de constructoras    
	url(r'^constructora_home/$', views.constructora_home, name='constructora_home'),
    url(r'^admin_file_upload/$', views.admin_file_upload, name='admin_file_upload'),
    url(r'^process_file/$', views.process_file, name='process_file'),
	#URL para crear un sensor en un plano
    url(r'^set_position_ajax/$', views.set_position_ajax, name='set_position_ajax'),
	#URL para eliminar un sensor en un plano
    url(r'^delete_position_ajax/$', views.delete_position_ajax, name='delete_position_ajax'),
    url('', include('django.contrib.auth.urls')),
    # URL- Reporte de eventos de los inmuebles de un propietario
    url(r'^rpt_owner_property/$', views.rpt_owner_property, name='rpt_owner_property'),
    # URL para generar en PDF el reporte de eventos de los inmuebles de un propietario
    url(r'^get_report_owner_property/$', views.get_report_owner_property, name='get_report_owner_property'),
    url(r'^get_report_admin_all_property/$', views.get_report_admin_all_property, name='get_report_admin_all_property'),
    # URL para consultar los datos del reporte de eventos de los inmuebles de un propietario
    url(r'^get_event_owner_property/$', views.get_event_owner_property, name='get_event_owner_property'),
    url(r'^get_event_admin_all_property/$', views.get_event_admin_all_property, name='get_event_admin_all_property'),
    url(r'^rpt_admin_all_property/$', views.rpt_admin_all_property, name='rpt_admin_all_property'),
    url(r'^rpt_admin_all_property_by_owner/$', views.rpt_admin_all_property_by_owner, name='rpt_admin_all_property_by_owner'),
    url(r'^get_event_admin_all_property_by_owner/$', views.get_event_admin_all_property_by_owner, name='get_event_admin_all_property_by_owner'),
    url(r'^get_report_admin_all_property_by_owner/$', views.get_report_admin_all_property_by_owner, name='get_report_admin_all_property_by_owner'),
    #url(r'^admin_file_upload/$', views.admin_file_upload, name='admin_file_upload'),
    url(r'^update_profile/$', views.update_profile, name='update_profile'),
)

watchapp/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from models import UserProfile

class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']
        widgets = {
            'password': forms.PasswordInput(),
        }

class ProfileForm(forms.Form):
	mobile_number = forms.CharField(label='Celular', max_length=15, required=True)
	email = forms.EmailField(label='Correo', required=True)
	password = forms.CharField(label='Contrasena', required=True, widget=forms.PasswordInput)
	file = forms.ImageField(label='Foto', required=True)

watchapp/views.py
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect, render_to_response
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib import messages 
from django.contrib.auth.models import User, Group
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.core.exceptions import ObjectDoesNotExist
from forms import SignUpForm
from watchapp.models import ConstructorCompany, Property, UserProfile, Sensor, Event
from watchapp.serializers import EventSerializer
from rest_framework import viewsets
import logging
from django.views.decorators.csrf import csrf_exempt
import json
import ho.pisa as pisa
import cStringIO as StringIO
import cgi
from django.template import RequestContext
from django.template.loader import render_to_string
import logging
import sys
import datetime
from django.core import serializers
import csv
from forms import ProfileForm
from django.core.mail import send_mail

log = logging.getLogger(__name__)

####################### Vistas index o para autenticacion #######################

def index(request):
	"""
	Esta vista es la pagina principal de WatchApp.
		@param request
		@author Lorena Salamanca
	"""
	return HttpResponse("Hello, world. You're at the watchapp index.")

def signup(request):
    """
    Esta funcion contiene el formulario de creacion de usuarios para WatchApp
    	@param request
    	@author Lorena Salamanca
    """
    if request.method == 'POST':  # If the form has been submitted...
        form = SignUpForm(request.POST)  # A form bound to the POST data
        if form.is_valid():  # All validation rules pass
 
            # Process the data in form.cleaned_data
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            email = form.cleaned_data["email"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
 
            # At this point, user is a User object that has already been saved
            # to the database. You can continue to change its attributes
            # if you want to change other fields.
            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
 
            # Save new user attributes
            user.save()
            return HttpResponseRedirect(reverse('watchapp:login'))  # Redirect after POST
    else:
        form = SignUpForm()
 
    data = {
        'form': form,
    }
    return render_to_response('watchapp/signup.html', data, context_instance=RequestContext(request))

def login_success(request):
    """
    Esta funcion redirecciona al home de constructoras o de usuarios (propietarios / residentes)
    dependiendo del Group al que pertenezca el usuario autenticado.
    	@param request
    	@author Lorena Salamanca
    """    
    if request.user.groups.filter(name="constructoras").exists():        
        return HttpResponseRedirect(reverse('watchapp:constructora_home'))
    elif request.user.groups.filter(name="usuarios").exists():       
        return HttpResponseRedirect(reverse('watchapp:users_home'))


@login_required()
def sensor_configuration(request):
    """
    Esta funcion tiene el contenido del home de usuarios (propietarios / residentes), 
    se puede acceder despues de la autenticacion de un usuario que este en el Group usuarios
    	@param request
    	@author Lorena Salamanca
    """
    if request.method == 'POST':
        sensors = []
	selected_property = Property.objects.get(name=request.POST["select_as_owner"])
	log.debug("Id Propiedad: " + str(selected_property.id))
	sensors = property_sensors(request,selected_property.id) 
        return render(request, 'watchapp/sensor_configuration.html', {
        "selected_property": selected_property,
        "request": request,
        "Sensors":sensors,
        })
    else:
        return render(request, 'watchapp/sensor_configuration.html', {
            "request": request,
        })


####################### Vistas para crear un sensor en un plano #######################

@login_required()
@csrf_exempt
def set_position_ajax(request):
        response_data = {}
	data = json.loads(request.body) 
        sensors = []
        selected_property = Property.objects.get(name=data['property'])
        sensor = Sensor(
		code = data['code'],
		description = data['description'],
		type =  data['type'],
		location_in_plan = data['location_in_plan'],
		is_discrete = data['location_in_plan'],
		property = selected_property,
		value = '0'
        )
        sensor.save()
	sensorUpdate=Sensor.objects.get(pk=sensor.pk)
        typeSensor =data['code']
        sensorUpdate.code = typeSensor[0]+'-'+str(sensor.pk);       
	sensorUpdate.save()
	sensors = property_sensors(request,selected_property.id) 
	print 'Add ok'
        data = {}
        data["sensor_id"] = sensorUpdate.id
        data["code"] = sensorUpdate.code
        data["location_in_plan"] = sensorUpdate.location_in_plan
        data["description"] = sensorUpdate.description
        data["type"] = sensorUpdate.type
        return HttpResponse(
                json.dumps(data),
                content_type="application/json"
            )


####################### Vistas para borrar un sensor en un plano #######################

@login_required()
@csrf_exempt
def delete_position_ajax(request):
        response_data = {}
	data = json.loads(request.body) 
        selected_property = Property.objects.get(name=data['property'])
	sensorUpdate=Sensor.objects.get(location_in_plan = data['location_in_plan'], property = selected_property)
	sensorUpdate.delete()
        response_data['msg'] = 'ok'
        return HttpResponse(
                json.dumps(data),
                content_type="application/json"
            )

####################### Vistas para propietarios / residentes #######################

@login_required()
@user_passes_test(lambda u: u.groups.filter(name='usuarios').exists(), login_url='/watchapp/login/')
def users_home(request):
    """
    Esta funcion tiene el contenido del home de usuarios (propietarios / residentes), 
    se puede acceder despues de la autenticacion de un usuario que este en el Group usuarios
    	@param request
    	@author Lorena Salamanca
    """
    if request.method == 'POST':
        sensors = []
        selected_property = ''
        asresident = 0;
        if request.POST.get('select_as_owner', '') == "0":
            selected_property = Property.objects.get(name=request.POST.get('select_as_resident', ''))
            sensors = property_sensors(request,selected_property.id)
            asresident = 1;
        elif request.POST.get('select_as_resident', '') == "0":
            selected_property = Property.objects.get(name=request.POST.get('select_as_owner', ''))
            log.debug("Id Propiedad: " + str(selected_property.id))
            sensors = property_sensors(request,selected_property.id)
        return render(request, 'watchapp/users_home.html', {
        "selected_property": selected_property,
        "asresident":asresident,
        "request": request,
        "Sensors":sensors,
        })
    else:
        return render(request, 'watchapp/users_home.html', {
            "request": request,
        })

@login_required()
@user_passes_test(lambda u: u.groups.filter(name='usuarios').exists(), login_url='/watchapp/login/')
def change_secure_mode(request, property_id, asresident):
    """
    Esta funcion activa / desactiva el modo seguro de un inmueble
        @param request
        @author Lorena Salamanca
    """
    if request.method == 'GET':
        selected_property = Property.objects.get(pk=property_id)
        if request.GET.get('change_secure_mode_checkbox', ''):
            selected_property.is_secure_mode = True
            selected_property.save()
        else:
            selected_property.is_secure_mode = False
            selected_property.save()
        sensors = property_sensors(request,selected_property.id)
        log.debug("change_secure_mode: Sensor secure mode val: " + str(selected_property.is_secure_mode))
        log.debug("change_secure_mode: asresident val: " + str(asresident))
        return render(request, 'watchapp/users_home.html', {
        "selected_property": selected_property,
        "request": request,
        "Sensors":sensors,
        "asresident":asresident,
        })

@login_required()
def render_sensor_status(request):
    """
    Esta funcion permite mostrar los datos que se mostraran en la pagina sensorstatus
        @param request
        @author German Bernal
    """      
    propertyList = propertys_by_User(request)    
    if request.method == 'POST':
        sensors = property_sensors(request,request.POST["select_Property"])        
        return render(request,"watchapp/sensorstatus.html",{
                "Sensors":sensors,
                "propertyList":propertyList
            })
    else:
        return render(request,"watchapp/sensorstatus.html",{
               "propertyList":propertyList
            })   
     
@login_required()
def property_sensors(request,property_id):
    """
    Esta funcion permite obtener los sensores por propiedad,
        @param request
        @author German Bernal
    """
    log.debug("property_sensors: val: " + str(property_id))
    sensors = Sensor.objects.filter(property_id=property_id)
    return sensors

@login_required()
def propertys_by_User(request):
    """
    Esta funcion permite obtener las propiedad por usuario.
        @param request
        @author German Bernal
    """    
    propertyList = []
    user = User.objects.filter(username=request.user.username)
    userP = UserProfile.objects.get(user_id=user[0].id)
    for p in userP.properties_as_resident.all():

watchapp/templates/watchapp/admin_file_upload.html
{% extends "watchapp/base.html" %} 

{% block content %} 
    {% if form.errors %}
        <p>Usuario y/o contraseña errados. Por favor intenta nuevamente.</p>
{% endif %} 
{% load url from future %}

<!-- DatePicker http://tarruda.github.io/bootstrap-datetimepicker/ -->
<link rel="stylesheet" href="{{ STATIC_URL }}css/styleSensor.css">
<link rel="stylesheet" href="{{ STATIC_URL }}css/fileinput.css" media="screen">
<script src="{{ STATIC_URL }}js/fileinput.js"></script>
<br />
<br />
<fieldset class="planContainer">
    <legend class="legendData">Importar Archivo de Inmueble</legend>
    <form enctype="multipart/form-data">
        {% csrf_token %}
        <input id="file-0" class="file" type="file" multiple data-min-file-count="1" data-show-upload="false" data-show-caption="true">
        <br>
        <div id="status"></div>
        <button type="button" class="btn btn-primary" onclick="upload_files();" >Guardar Inmuebles</button>
    </form>
</fieldset>
<script>
    $("#file-0").fileinput({
        'allowedFileExtensions': ['csv'],
	browseClass: "btn btn-primary",
	browseLabel: "Carga archivo",
	removeClass: "btn btn-primary",
	removeLabel: "Borrar",
    });

    function upload_files(){
        var files = $("#file-0")[0].files;
        var csrf_token = $('input[name="csrfmiddlewaretoken"]');
        var ctrlId = "status";
        if(files.length > 0){
            var formData = new FormData();
            formData.append("property_file", files[0]);
            var uploadServerSideScriptPath = "/watchapp/process_file/";
            var xhr = new XMLHttpRequest();
            xhr.open("POST", uploadServerSideScriptPath, true);
            xhr.upload.addEventListener('progress', function (e) {
                $('#' + ctrlId).html("<span style='color: blue'>Cargando...</span>");
            });
            xhr.addEventListener("readystatechange", function (e) {                
                if (this.readyState === 4 & this.status == 200) {
                    var response = JSON.parse(this.response);
                    $(".close").trigger("click");                                 
                    $('#' + ctrlId).fadeIn("slow", function () {
                        $('#' + ctrlId).html("<span style='color: " + (response.valid ? "green" : "red") + "'>" + response.message + "</span>");
                        $('#' + ctrlId).fadeOut(3000);                               
                    });
                }
                else if(this.status == 500){
                    alert(this.response);
                    $('#' + ctrlId).html("<span style='color: Red'>" + this.responseText + "</span>");
                    $('#' + ctrlId).fadeIn("slow", function () { });
                }            
            });
            xhr.setRequestHeader("X-CSRFToken", $(csrf_token).val());
            xhr.send(formData);
        }
    }
</script>
{% endblock %}

watchapp/templates/watchapp/constructora_home.html
{% extends "watchapp/base.html" %}
 
{% block content %}
    {% if form.errors %}
        <p>Usuario y/o contraseña errados. Por favor intenta nuevamente.</p>
{% endif %}
 {% load url from future %}
 
    <div class="datagrid" style="width: 90%;">
        <table style="width: 100%;">
            <thead>
                <tr>
                    <td colspan="2">
                        <article class="col-sm-8 maincontent">
                            <header class="page-header">
                                <h1 class="page-title">Bienvenido Constructora!</h1>
                            </header>
                            <p>Bienvenido <strong>{{ user.first_name }} {{ user.last_name }}</strong>,</p>

                            <p>Tú última visita a WatchApp fue {{ user.last_login }} </p>
                        </article>
                    </td>
                </tr>
            </thead>
            
<tbody> 
                        </tbody>
        </table>
    </div>
    <br />
    <br />
{% endblock %}

watchapp/templates/watchapp/home.html
{% extends "watchapp/base.html" %}
 
{% block content %}
 
    <table>
        <tr>
            <td>{{ user.username.label_tag }}</td>
            <td>{{ user.username }}</td>
        </tr>
 
        <tr>
            <td>{{ user.email.label_tag }}</td>
            <td>{{ user.email }}</td>
        </tr>
 
        <tr>
            <td>{{ user.first_name.label_tag }}</td>
            <td>{{ user.first_name }}</td>
        </tr>
 
        <tr>
            <td>{{ user.last_name.label_tag }}</td>
            <td>{{ user.last_name }}</td>
        </tr>
 
        <tr>
            <td>{{ user.date_joined.label_tag }}</td>
            <td>{{ user.date_joined }}</td>
        </tr>
 
        <tr>
            <td>{{ user.last_login.label_tag }}</td>
            <td>{{ user.last_login }}</td>
        </tr>
 
    </table>
 
    <a href="{% url 'watchapp:logout' %}">Logout</a>
 
 
{% endblock %}

watchapp/templates/watchapp/login.html
{% extends "watchapp/base _master.html" %}
 
{% block content %}
    {% if form.errors %}
        <p>Usuario y/o contraseña errados. Por favor intenta nuevamente.</p>
    {% endif %}
 {% load url from future %}
<style>

input[type=text], input[type=password]{
    display: block;
    width: 100%;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.428571429;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}

    input[type=text]:focus , input[type=password]:focus {
        border-color: #66afe9;
        outline: 0;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
    }
</style>
  <form method="post" action="{% url 'watchapp:django.contrib.auth.views.login' %}">
        {% csrf_token %}
            <!-- Article main content -->
                    <h1 class="page-title">Sign in</h1>
<hr>
                      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
  <a href="{% url 'watchapp:signup' %}" class="nuevoContacto" style="font-weight: bold;">Register</a>
                            <hr>
                            <form>
                                <div class="top-margin">
					<div  >{{ form.username.label_tag }}</div>
					<div>{{ form.username}}</div>               
                                </div>
                                <div class="top-margin">
					<div>{{ form.password.label_tag }}</div>
					<div>{{ form.password }}</div>
                                </div>
                                <hr> 
                                <div class="row">
                                    <div class="col-lg-8">
                                       
                                    </div>
                                    <div class="col-lg-4 text-right">
					<input type="submit" value="Sign in" class="btn btn-action" /> 
					<input type="hidden" name="next" value="{{ next }}"/>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </article>
            <!-- /Article -->
 <br/>
       
    </form> 
{% endblock %}

watchapp/templates/watchapp/sensorstatus.html
{% extends "watchapp/base.html" %} 

{% block content %} 
    {% if form.errors %}
        <p>Usuario y/o contraseña errados. Por favor intenta nuevamente.</p>
    {% endif %} 
{% load url from future %}

<!DOCTYPE html>
<html>
<body>
    <h1 id="header">
        Sensores</h1>
    <br />
    <br />
    <br />
    <div class="datagrid" style="width: 90%;">
        <form method="post" action="{% url 'watchapp:render_sensor_status' %}" id="get_property_sensor_by_id">
        {% csrf_token %}
            <div>
    	        <label>Inmuebles</label> 
    	        <select id="select_Property" name="select_Property" onchange="onchange_property();">
    		        <option value="0">Selecciona...</option>
    		        {% for p in propertyList %}
    			        <option value="{{ p.id }}">{{ p.name }}</option>
    		        {% endfor %}
    	        </select>
            </div>
        </form>
        <table style="width: 100%;">
            <thead>
                <tr>
                    <th>
                        Sensores
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <div>
                            {% if Sensors %} 
                                <table>
                                    <tbody>
                                        <tr>
                                            <td>Código</td>
                                            <td>Descripción</td>
                                            <td>Tipo</td>
                                            <td>Ubicación</td>
                                            <td>Color</td>
                                            <td>Estado</td>
                                         </tr>
                                         {% for Sensor in Sensors%}

                                         <tr>
                                            <td>{{ Sensor.code }}</td>
                                            <td>{{Sensor.description}}</td>
                                            <td>{{Sensor.type}}</td>
                                            <td>{{Sensor.location_in_plan}}</td>
                                            <td>{{Sensor.color}}</td>
                                            <td>{{Sensor.status}}</td>
                                         </tr>
                                         {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                            <p>
                                No hay Sensores.</p>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <br />
    <br />
    </div>

    <script type="text/javascript">
        function onchange_property(){                
                document.getElementById("get_property_sensor_by_id").submit();
        }
    </script>
</body>
</html>

{% endblock %}

watchapp/templates/watchapp/signup.html
{% extends "watchapp/base _master.html" %}
{% block content %}
 
    {% if form.errors %}
        <p>{{ form.errors }}</p>
    {% endif %}
 <style>

input[type=text], input[type=password], input[type=email]{
    display: block;
    width: 100%;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.428571429;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}

    input[type=text]:focus , input[type=password]:focus , input[type=email]:focus{
        border-color: #66afe9;
        outline: 0;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
    }
</style>
    <form method="post" action="{% url 'watchapp:signup' %}">
 
        {% csrf_token %}
   <div class="form-group">
</div>
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Register a new account</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
  			   <form>
                                <div class="top-margin">
					{{ form.username.label_tag }}
					{{ form.username }}
                                </div>
                                <div class="top-margin">
					{{ form.password.label_tag }}
					{{ form.password }}
                                </div>
                                <div class="top-margin">
					{{ form.email.label_tag }}
					{{ form.email }}
                                </div>

                                <div class="row top-margin">
                                    <div class="col-sm-6">
					{{ form.first_name.label_tag }}
					{{ form.first_name }}
                                    </div>
                                    <div class="col-sm-6">
					{{ form.last_name.label_tag }}
					{{ form.last_name }}
                                    </div>
                                </div>

                                <hr>

                                <div class="row">
                                    <div class="col-lg-8">
					 <a href="{% url 'watchapp:login' %}" style="font-weight:bold;">Login</a>
                                    </div>
                                    <div class="col-lg-4 text-right">
       					<input type="submit" value="Register" class="btn btn-action" />
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </article>
            <!-- /Article -->
    </form>
{% endblock %}

watchapp/templates/watchapp/update_profile.html
{% extends "watchapp/base.html" %} 

{% block content %} 
    {% if form.errors %}
        <p></p>
{% endif %} 
{% load url from future %}
<style>
.uploadStyle
{
width: 100px
}
</style>

<!-- DatePicker http://tarruda.github.io/bootstrap-datetimepicker/ -->
<link rel="stylesheet" href="{{ STATIC_URL }}css/styleSensor.css">
<link rel="stylesheet" href="{{ STATIC_URL }}css/fileinput.css" media="screen">
<script src="{{ STATIC_URL }}js/fileinput.js"></script>
<br />
<br />
{% if actualizado %}
	<div class="alert-info">Perfil actualizado!!!</div>
{% endif %}
<!--fieldset class="planContainer">
    <legend class="legendData">Sprint 3 -  HU(WAT - 10)</legend>
    <p>
Como desarrollador, yo permito a los usuarios actualizar la información de su perfil (contraseña, email, número de celular, foto) de forma que un usuario tenga su información personal actualizada para recibir notificaciones.
    </p>
</fieldset-->

  <form method="post" enctype="multipart/form-data" action="{% url 'watchapp:update_profile' %}">
        {% csrf_token %}

<fieldset class="planContainer">
    <legend class="legendData">Actualizar Perfil</legend>
            <div style="width: 100%; margin: 0; text-align: center;">
            <table style="margin: 0 auto;width: 800px;" class="planContainer">
                <tr>
                    <td style="width: 100%;" colspan="5">
 <h1 class="page-title">{{ user.first_name }} {{ user.last_name }}</h1>
                    </td>
                    <td></td>
		    <td></td>
                </tr>
                <tr>
<td  style="width: 50px;" ></td>
                    <td style="height: 100px; width: 200px;">
<img src="{{ STATIC_URL }}images/{{user.userprofile.photo}}" alt="WatchApp" style="background-size: cover;height: 100px; width: 100px;">
                        <!--input id="file-0" class="file" accept="image/*" type="file" multiple data-min-file-count="1" data-show-upload="false" data-show-caption="true" -->
                    </td>
		    <td  style="width: 50px;"></td>
                    <td>
                        <table>
				{{ form.as_table }}
                          <tr>
                                <td style="width: 200px;" colspan="5">

                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>  
            </table>
        </div>
</fieldset>

</form>

<script>
    $("#file-0").fileinput({
        'allowedFileExtensions': ["jpg", "gif", "png"],
        previewFileType: "image",
	browseClass: "btn btn-primary",
	browseLabel: "Carga Foto del Perfil",
	removeClass: "btn btn-primary",
	removeLabel: "Borrar",
width: '120px', 
    });
</script>
{% endblock %}